# Generated by Django 2.1 on 2018-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Working_on'), (2, 'Complete'), (3, 'Reject')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='venture',
            field=models.IntegerField(blank=True, choices=[(0, 'Individual'), (1, 'Joint_venture')], default=0, null=True),
        ),
    ]
