# Generated by Django 2.0.5 on 2018-08-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180825_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='due_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
